- name: prepare
  hosts: all
  gather_facts: no  # не используем сбор фактов для ускорения выполнения
  become: yes
  vars:
    rabbitmq_hosts: |
      192.168.0.114 Deb11-x64-hw03      
      192.168.0.148 Deb11-x64
    rabbitmq_cluster_master: Deb11-x64
    update_hosts: true
    rabbitmq_create_cluster: yes
    rabbitmq_erlang_cookie: WKRBTTEQRYPTQOPUKSVF
    rabbitmq_plugins:
      - rabbitmq_management
#      - rabbitmq_management_agent
#      - rabbitmq_shovel
#      - rabbitmq_shovel_management
#Handlers are tasks that only run when notified.
  handlers:
    - name: stop rabbitmq-server
      service: name=rabbitmq-server state=stopped
    - name: restart rabbitmq-server
      service: name=rabbitmq-server state=restarted
    - name: start rabbitmq-server
      service: name=rabbitmq-server state=started
  tasks:
    - name: "Istall team RabbitMQ's main signing key"
      ansible.builtin.get_url:
        url: https://keys.openpgp.org/vks/v1/by-fingerprint/0A9AF2115F4687BD29803A206B73A36E6026DFCA
        dest: /usr/share/keyrings/com.rabbitmq.team.asc
        mode: '0644'
        force: true
    - name: "Community mirror of Cloudsmith: modern Erlang repository"
      ansible.builtin.get_url:
        url: https://github.com/rabbitmq/signing-keys/releases/download/3.0/cloudsmith.rabbitmq-erlang.E495BB49CC4BBE5B.key
        dest: /usr/share/keyrings/rabbitmq.E495BB49CC4BBE5B.asc
        mode: '0644'
        force: true
    - name: "Community mirror of Cloudsmith: RabbitMQ repository"
      ansible.builtin.get_url:
        url: https://github.com/rabbitmq/signing-keys/releases/download/3.0/cloudsmith.rabbitmq-server.9F4587F226208342.key
        dest: /usr/share/keyrings/rabbitmq.9F4587F226208342.asc
        mode: '0644'
        force: true
    - name: "create repo file"
      ansible.builtin.copy:
        dest: /etc/apt/sources.list.d/rabbitmq.list
        content: |
          ## Provides modern Erlang/OTP releases from a Cloudsmith mirror
          ##
          deb [signed-by=/usr/share/keyrings/rabbitmq.E495BB49CC4BBE5B.asc] https://ppa1.novemberain.com/rabbitmq/rabbitmq-erlang/deb/debian bullseye main
          deb-src [signed-by=/usr/share/keyrings/rabbitmq.E495BB49CC4BBE5B.asc] https://ppa1.novemberain.com/rabbitmq/rabbitmq-erlang/deb/debian bullseye main
          
          deb [signed-by=/usr/share/keyrings/rabbitmq.E495BB49CC4BBE5B.asc] https://ppa2.novemberain.com/rabbitmq/rabbitmq-erlang/deb/debian bullseye main
          deb-src [signed-by=/usr/share/keyrings/rabbitmq.E495BB49CC4BBE5B.asc] https://ppa2.novemberain.com/rabbitmq/rabbitmq-erlang/deb/debian bullseye main
          
          ## Provides RabbitMQ from a Cloudsmith mirror
          ##
          deb [signed-by=/usr/share/keyrings/rabbitmq.9F4587F226208342.asc] https://ppa1.novemberain.com/rabbitmq/rabbitmq-server/deb/debian bullseye main
          deb-src [signed-by=/usr/share/keyrings/rabbitmq.9F4587F226208342.asc] https://ppa1.novemberain.com/rabbitmq/rabbitmq-server/deb/debian bullseye main
          
          # another mirror for redundancy
          deb [signed-by=/usr/share/keyrings/rabbitmq.9F4587F226208342.asc] https://ppa2.novemberain.com/rabbitmq/rabbitmq-server/deb/debian bullseye main
          deb-src [signed-by=/usr/share/keyrings/rabbitmq.9F4587F226208342.asc] https://ppa2.novemberain.com/rabbitmq/rabbitmq-server/deb/debian bullseye main
    - name: update apt cache
      apt:
        update_cache: yes
#    - name: perform upgrade of all packages to the latest version
#      apt:
#        upgrade: dist
#        force_apt_get: yes
    - name: install pip
      apt:
        name: 
          - python3
          - python3-pip
        state: fixed
      changed_when: false
    - name: install python pika
      pip:
        name:
          - pika
        executable: pip3
    - name: update apt cache
      apt:
        update_cache: yes
#    - name: perform upgrade of all packages to the latest version
#      apt:
#        upgrade: dist
#        force_apt_get: yes
    - name: install python pika
      pip:
        name:
          - pika
        executable: pip3
    - name: install Erlang packages and Deps
      apt:
        name:
          - curl
          - gnupg
          - apt-transport-https
          - erlang-base
          - erlang-asn1
          - erlang-crypto
          - erlang-eldap
          - erlang-ftp
          - erlang-inets
          - erlang-mnesia
          - erlang-os-mon
          - erlang-parsetools
          - erlang-public-key
          - erlang-runtime-tools
          - erlang-snmp 
          - erlang-ssl
          - erlang-syntax-tools
          - erlang-tftp
          - erlang-tools
          - erlang-xmerl
    - name: install Rabbitmq
      apt:
        name: rabbitmq-server
        state: fixed
    - name: change hosts
      blockinfile:
        path: /etc/hosts
        block: "{{ rabbitmq_hosts }}"
        owner: root
        group: root
        mode: 0644
      when: update_hosts

    - name: backup old erlang cookie
      shell: cp -a /var/lib/rabbitmq/.erlang.cookie /var/lib/rabbitmq/.erlang.cookie.old
      changed_when: false
#Таск для копирования файла-шаблона erlang.cookie в целевую директорию с заданным владельцем и правами
    - name: updating rabbitmq erlang cookie 
      template:
        src: erlang.cookie.j2
        dest: /var/lib/rabbitmq/.erlang.cookie
        owner: rabbitmq
        group: rabbitmq
        mode: 0400
#Tasks can instruct one or more handlers to execute using the notify keyword. The notify keyword can be applied to a task and accepts a list of handler names that are notified on a task change.
      notify:
        restart rabbitmq-server
      when: rabbitmq_create_cluster
#Meta tasks are a special kind of task which can influence Ansible internal execution or state. flush_handlers makes Ansible run any handler tasks which have thus far been notified.
    - meta: flush_handlers

    - name: remove old erlang cookie
      file:
        path: /var/lib/rabbitmq/.erlang.cookie.old
        state: absent
      changed_when: false
#Включаем менеджмент плагин
    - name: Enable the plugins is installed
      rabbitmq_plugin:
        names: "{{ item }}"
#        prefix: /usr/lib/rabbitmq
        state: enabled
#        new_only: yes
      with_items: "{{ rabbitmq_plugins }}"
      notify:
        restart rabbitmq-server
#Запускаем службу    
    - name: rabbitmq service started and enabled
      service:
        name: rabbitmq-server
        enabled: yes
        state: started
#Добавляем текущий хост в кластер
    - name: add to cluster
      block:
        - name: stop rabbitmq app
          command: rabbitmqctl stop_app

        - name: add this node to cluster
          command: rabbitmqctl join_cluster rabbit@{{ rabbitmq_cluster_master }}

        - name: start rabbitmq app
          command: rabbitmqctl start_app
#      when: rabbitmq_create_cluster == "yes"
#Добавляем нового пользователя и назначение ему прав и тега. rc 70: user already exists
    - name: create rabbitmqSTR user
      shell: rabbitmqctl add_user rabbitmqSTR qwerty
      register: res
      failed_when: res.rc != 70 and res.rc != 0
      changed_when: res.rc != 70

    - name: list permissions for rabbitmqSTR user
      shell: rabbitmqctl list_permissions
      register: list_permissions
      changed_when: false

    - name: set permissions on / vhost
      shell: rabbitmqctl set_permissions rabbitmqSTR ".*" ".*" ".*"
      when: list_permissions.stdout.find("rabbitmqSTR") == -1

    - name: set user tag
      shell: rabbitmqctl set_user_tags rabbitmqSTR administrator
      when: list_permissions.stdout.find("rabbitmqSTR") == -1
#Проверяем политики репликации очередей в кластере и назначем ha-all
    - name: check if ha-mode is already enabled
      shell: rabbitmqctl list_policies
      register: list_policies
      changed_when: false

    - name: set ha-mode to exactly two nodes for all queues for backup
      shell: rabbitmqctl set_policy ha-all "" '{"ha-mode":"all","ha-sync-mode":"automatic"}'
      register: res
      failed_when: res.rc != 0
      when: list_policies.stdout.find("ha-all") == -1
